### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [neurodebian/dockerfiles#10]
Hi,

The NeuroDebian docker package is building and running fine at my end for ARM64v8 architecture.

Branch used to build is: 
````
stretch
````
Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by yarikoptic** [comment]
We need to ask the expert, @tianon ;-) how do we enable arm builds if possible?

Happy holidays (if applies) ;-)

**Comment by lag-linaro** [comment]
Enabling ARM64v8 is trivial.

Simply add the Architectures tag to each entry in [THIS](https://github.com/docker-library/official-images/blob/master/library/neurodebian) file which supports ARM64v8.

As a related aside, is there any reason for not supplying ARM64v8 packages for Ubuntu?

See [HERE](http://neuro.debian.net/debian-devel/dists/bionic/main/) for reference.

**Comment by yarikoptic** [comment]
We have no juice, infrastructure and demand to support arm properly in NeuroDebian ATM

**Comment by yarikoptic** [comment]
Which gave me now obvious realization that there is no reason to provide NeuroDebian docker images for arm ATM, so I will close this issue.

**Comment by odidev** [comment]
@yarikoptic : Is there any way that we can provide you with enough confidence to have demand for ```ARM``` in a market?
Right now, what we can notice is that paradigm is shifting towards more and more use of ARM-based architectures in the market.
And that's the reason that more and more docker repositories have started their work to extend support for ARM as well.
In my view, this is a good time to extend ```NeuroDebian``` as well for ```ARM64```, so as to remain ahead in market and gain as many consumers possible.

**Comment by yarikoptic** [comment]
Once again, we do not provide arm builds from NeuroDebian ATM, since there so far were no demand in our field of neuroimaging. Those who tried, just use regular Debian where we upload majority of our packages. So what would be the point, besides providing backports of just a few architecture agnostic backports and cusing pains whenever their arch dependent parts aren't available? So, until we have "consumers" demanding arm builds and some juice to provide them, I would prefer not to mudder the waters

**Comment by mmarmm** [comment]
@yarikoptic Hi Yaroslav,

I appreciate your position and what you said above makes sense. The only thing that I would add would be to comment for people possibly experimenting with NeuroDebian on Raspberry PIs or even larger systems like ThunderX (96 cores via packet.net which are cheap and efficient) - I would hope that people will be able to build this themselves without too much extra trouble but here's additional information:

Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Arm Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/

Thank you again and I hope we can help generate demand for ND on Arm.

**Comment by lag-linaro** [comment]
Great info @mmarmm, thanks for that.

@yarikoptic if you change your mind and wish for additional help/support to set up the infrastructure or with testing, please let me know.

**Comment by yarikoptic** [comment]
Will do, thanks @lag-linaro and @mmarmm

**Comment by odidev** [comment]
@yarikoptic If you are interested in providing neurodebian docker images for arm64 now, I am happy to raise a PR. Please share your opinion.
