### ISSUE TITLE
Build get stuck on survey needing user input

### ISSUE THREAD

**Issue by sonn-gamm** [neurodebian/dockerfiles#15]
When adding `FROM neurodebian' to a dockerfile, the image get stuck at:

```
[...]
Participate in the package usage survey? [yes/no]
```

Is there any tip or extra config I should use to skip / move the build forward?

**Comment by yarikoptic** [comment]
sorry about the delay! best practices could be looked up within  https://github.com/ReproNim/neurodocker or produced by it container recipes. E.g. in https://github.com/ReproNim/reproin/blob/HEAD/Dockerfile#L15 we have

```
ARG DEBIAN_FRONTEND="noninteractive"
```
and then
```
dpkg-reconfigure --frontend=noninteractive locales
```
for that specific package reconfiguration.

Hope this helps
