### ISSUE TITLE
Tag debian base images based on version number rather than name

### ISSUE THREAD

**Issue by asmacdo** [neurodebian/dockerfiles#16]
More descriptive, and could be used programatically

**Comment by yarikoptic** [comment]
what do you mean? we already tag by version as well, look at https://hub.docker.com/_/neurodebian  e.g.

[bionic, nd18.04](https://github.com/neurodebian/dockerfiles/blob/1da9308291ad33a33447519ec1835bb3e37acebc/dockerfiles/bionic/Dockerfile)
[bionic-non-free, nd18.04-non-free](https://github.com/neurodebian/dockerfiles/blob/1da9308291ad33a33447519ec1835bb3e37acebc/dockerfiles/bionic-non-free/Dockerfile)
