### ISSUE TITLE
Add DEBIAN_FRONTEND="noninteractive" to all images

### ISSUE THREAD

**Issue by asmacdo** [neurodebian/dockerfiles#17]
Container base images should always be assumed to be noninteractive since they are intended to be used in Containerfiles.

Add this to all images.

**Comment by yarikoptic** [comment]
"Not sure" -- it might be up to specific use case to either disable or enable interactivity.  It might be installing/configuring interactively.   We might want to improve documentation somewhere/how though.

**Comment by asmacdo** [comment]
In what case would a base image be used interactively?

**Comment by yarikoptic** [comment]
when I (or anyone else) just needs to recreate (may be just temporarily) some environment.  I do that from time to time, e.g. to troubleshoot package building or testing within neurodebian environments. just running `docker run -it --rm` on them.  Do we know inside the docker container if it was ran with `-i`  - may be we need to look more into that detection, but I not sure even if it is at our level (and not deeper in `debconf`)

**Comment by tianon** [comment]
See https://bugs.debian.org/929417, which _should_ finally be fixed in bookworm+ :eyes:

**Comment by yarikoptic** [comment]
Thank you @tianon for the reference!

Anyways and overall I do not think we should add such env var, thus I will close.
