### ISSUE TITLE
remove a porn url from the comments on the hub

### ISSUE THREAD

**Issue by yarikoptic** [neurodebian/dockerfiles#6]
see at the bottom of the page https://hub.docker.com/_/neurodebian/ 

@tianon I think I have no authority over that page/comments. whom should I pester? ;)

**Comment by tianon** [comment]
Euch, probably support@docker.com -- I don't have any better contacts to
help, unfortunately.

**Comment by yarikoptic** [comment]
I do not see anything evil any more on that page -- I guess dealt with centrally.
